public class RoutineMng extends javax.swing.JFrame {

    // Creates new form RoutineMng
    public RoutineMng() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BusTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        PlaneTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TrainTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAddBus = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnAddPlane = new javax.swing.JButton();
        btnAddTrain = new javax.swing.JButton();
        txtBusNum = new javax.swing.JTextField();
        txtBusTo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBusArrival = new javax.swing.JTextField();
        txtBusDepart = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBusFrom = new javax.swing.JTextField();
        txtTrainArrival = new javax.swing.JTextField();
        txtTrainDepart = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTrainFrom = new javax.swing.JTextField();
        txtTrainNum = new javax.swing.JTextField();
        txtTrainTo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPlaneArrival = new javax.swing.JTextField();
        txtPlaneDepart = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPlaneFrom = new javax.swing.JTextField();
        txtPlaneNum = new javax.swing.JTextField();
        txtPlaneTo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnSaveTrain = new javax.swing.JButton();
        btnDeleteBus = new javax.swing.JButton();
        btnDeletePlane = new javax.swing.JButton();
        btnDeleteTrain = new javax.swing.JButton();
        btnSavePlane = new javax.swing.JButton();
        btnSaveBus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BusTable.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        BusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Bus #", "From", "To", "Departure Time", "Arrival Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BusTable);

        PlaneTable.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        PlaneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Plane #", "From", "To", "Departure Time", "Arrival Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PlaneTable);

        TrainTable.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        TrainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Train #", "From", "To", "Departure Time", "Arrival Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TrainTable);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel1.setText("Bus Number");

        btnAddBus.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        btnAddBus.setText("Add Bus");
        btnAddBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBusActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        btnHome.setText("Home");
        btnHome.setActionCommand("Save Changes");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnAddPlane.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        btnAddPlane.setText("Add Plane");
        btnAddPlane.setActionCommand("Home");
        btnAddPlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPlaneActionPerformed(evt);
            }
        });

        btnAddTrain.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        btnAddTrain.setText("Add Train");
        btnAddTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTrainActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel4.setText("Departure Time");

        jLabel5.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel5.setText("From");

        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel6.setText("To");

        jLabel7.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel7.setText("Arrival Time");

        jLabel8.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel8.setText("Arrival Time");

        jLabel9.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel9.setText("Departure Time");

        jLabel10.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel10.setText("From");

        jLabel11.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel11.setText("To");

        jLabel12.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel12.setText("Train Number");

        jLabel13.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel13.setText("Arrival Time");

        jLabel14.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel14.setText("Departure Time");

        jLabel15.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel15.setText("From");

        jLabel16.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel16.setText("To");

        jLabel17.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel17.setText("Plane Number");

        btnSaveTrain.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        btnSaveTrain.setText("Save");
        btnSaveTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTrainActionPerformed(evt);
            }
        });

        btnDeleteBus.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        btnDeleteBus.setText("Delete");
        btnDeleteBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBusActionPerformed(evt);
            }
        });

        btnDeletePlane.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        btnDeletePlane.setText("Delete");
        btnDeletePlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePlaneActionPerformed(evt);
            }
        });

        btnDeleteTrain.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        btnDeleteTrain.setText("Delete");
        btnDeleteTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTrainActionPerformed(evt);
            }
        });

        btnSavePlane.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        btnSavePlane.setText("Save");
        btnSavePlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePlaneActionPerformed(evt);
            }
        });

        btnSaveBus.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        btnSaveBus.setText("Save");
        btnSaveBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBusNum)
                                    .addComponent(txtBusTo)
                                    .addComponent(txtBusArrival)
                                    .addComponent(txtBusDepart)
                                    .addComponent(txtBusFrom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddBus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDeleteBus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSaveBus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTrainNum)
                                    .addComponent(txtTrainTo)
                                    .addComponent(txtTrainArrival)
                                    .addComponent(txtTrainDepart, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTrainFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDeleteTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSaveTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHome)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPlaneNum)
                                    .addComponent(txtPlaneTo)
                                    .addComponent(txtPlaneArrival)
                                    .addComponent(txtPlaneDepart, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPlaneFrom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddPlane)
                                    .addComponent(btnDeletePlane, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSavePlane, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtBusNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddBus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtBusFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(btnDeleteBus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(btnSaveBus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrainNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(btnAddTrain))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTrainFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(btnDeleteTrain))
                            .addComponent(txtTrainTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrainDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrainArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(btnSaveTrain))
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlaneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(btnAddPlane))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtPlaneFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeletePlane)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPlaneTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlaneDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlaneArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(btnSavePlane))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHome))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Send user back to home page
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    // BUS TABLE // 
    private void btnAddBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBusActionPerformed
        String busNum = tfFirstName.getText();
        String busStartPoint = tfLastName.getText();
        String BusEndPoint = tfContactEmail.getText();
        String = tfBirthDate.getDate();
        String username = tfUsername.getText();
        
    }//GEN-LAST:event_btnAddBusActionPerformed

    private void btnDeleteBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBusActionPerformed
        String busNum = tfFirstName.getText();
        String startPoint = tfLastName.getText();
        String endPoint = tfContactEmail.getText();
        String = tfBirthDate.getDate();
        String username = tfUsername.getText();
    }//GEN-LAST:event_btnDeleteBusActionPerformed

    private void btnSaveBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBusActionPerformed
        
    }//GEN-LAST:event_btnSaveBusActionPerformed

    
    // TRAIN TABLE // 
    private void btnAddTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTrainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTrainActionPerformed

    private void btnDeleteTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTrainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteTrainActionPerformed

    private void btnSaveTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTrainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveTrainActionPerformed

    
    // PLANE TABLE //
    private void btnAddPlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPlaneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPlaneActionPerformed

    private void btnDeletePlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePlaneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletePlaneActionPerformed

    private void btnSavePlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePlaneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSavePlaneActionPerformed
    


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoutineMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoutineMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoutineMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoutineMng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoutineMng().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BusTable;
    private javax.swing.JTable PlaneTable;
    private javax.swing.JTable TrainTable;
    private javax.swing.JButton btnAddBus;
    private javax.swing.JButton btnAddPlane;
    private javax.swing.JButton btnAddTrain;
    private javax.swing.JButton btnDeleteBus;
    private javax.swing.JButton btnDeletePlane;
    private javax.swing.JButton btnDeleteTrain;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSaveBus;
    private javax.swing.JButton btnSavePlane;
    private javax.swing.JButton btnSaveTrain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtBusArrival;
    private javax.swing.JTextField txtBusDepart;
    private javax.swing.JTextField txtBusFrom;
    private javax.swing.JTextField txtBusNum;
    private javax.swing.JTextField txtBusTo;
    private javax.swing.JTextField txtPlaneArrival;
    private javax.swing.JTextField txtPlaneDepart;
    private javax.swing.JTextField txtPlaneFrom;
    private javax.swing.JTextField txtPlaneNum;
    private javax.swing.JTextField txtPlaneTo;
    private javax.swing.JTextField txtTrainArrival;
    private javax.swing.JTextField txtTrainDepart;
    private javax.swing.JTextField txtTrainFrom;
    private javax.swing.JTextField txtTrainNum;
    private javax.swing.JTextField txtTrainTo;
    // End of variables declaration//GEN-END:variables
}
