import java.sql.*;
import javax.swing.JOptionPane;

public class UserProfile extends javax.swing.JFrame {


    // Creates new form UserProfile
    public UserProfile() {
        initComponents();
        this.setLocationRelativeTo(null);
        userInformation(HomePage.ActiveUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPhoneNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBirthDate = new javax.swing.JTextField();
        

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 0, 20)); // NOI18N
        jLabel1.setText("PROFILE DETAILS");

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        jLabel3.setText("NAME");

        jLabel4.setFont(new java.awt.Font("SimSun-ExtB", 0, 20)); // NOI18N
        jLabel4.setText("Contact Details");

        jLabel5.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        jLabel5.setText("DATE OF BIRTH");

        jLabel6.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        jLabel6.setText("USERNAME");

        jLabel7.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        jLabel7.setText("PHONE NUMBER");

        jLabel8.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        jLabel8.setText("EMAIL");

        btnSave.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        btnSave.setText("Save Changes");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnGoBack.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        btnGoBack.setText("Close Profile");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(179, 0, 0));

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 0, 36)); // NOI18N
        jLabel2.setText("User Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(163, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel2)
                                .addContainerGap(24, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addGap(47, 47, 47))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel8)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jLabel7)
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jLabel6)
                                                                                                .addComponent(jLabel5)
                                                                                                .addComponent(
                                                                                                        jLabel3))))
                                                                        .addComponent(btnGoBack))
                                                                .addGap(18, 18, 18)))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                260, Short.MAX_VALUE)
                                                        .addComponent(txtFullName)
                                                        .addComponent(txtPhoneNum)
                                                        .addComponent(txtEmail)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(btnSave,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 151,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(45, 45, 45))
                                                        .addComponent(txtBirthDate,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 260,
                                                                Short.MAX_VALUE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addGap(104, 104, 104))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(txtFullName,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel3))
                                                                .addGap(17, 17, 17)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(txtUsername,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel6))
                                                                .addGap(17, 17, 17)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(txtBirthDate,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(80, 80, 80)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(txtPhoneNum,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel7))
                                                                .addGap(31, 31, 31)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(txtEmail,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel8))))
                                                .addGap(35, 98, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnGoBack, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(25, 25, 25)))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userInformation(String ActiveUser) {
    try {Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/TransModus", "root", ""); // Establish connection with SQL Database
        // Prepare the SQL statement to retrieve the data
        PreparedStatement statement = connection.prepareStatement("SELECT firstname, lastname, login, phone_number, email, birthday_month, birthday_day, birthday_year FROM client WHERE client_id = ?");
        statement.setString(1, ActiveUser);
        // Execute the query
        ResultSet resultSet = statement.executeQuery();

        if (resultSet.next()) {
            // Retrieve the values from the result set
            String firstname = resultSet.getString("firstname");
            String lastname = resultSet.getString("lastname");
            String name = firstname + ' ' + lastname;
            
            String login = resultSet.getString("login");
           
            String phoneNumber = resultSet.getString("phone_number");
            
            String email = resultSet.getString("email");
            
            String birthdayMonth = resultSet.getString("birthday_month");
            String birthdayDay = resultSet.getString("birthday_day");
            String birthdayYear = resultSet.getString("birthday_year");
            String dateofBirth = birthdayMonth + " " + birthdayDay + ", " + birthdayYear;


            // Populate the text fields with the retrieved values
            
            txtFullName.setText(name);
            txtUsername.setText(login);
            txtPhoneNum.setText(phoneNumber);
            txtEmail.setText(email);
            txtBirthDate.setText(dateofBirth);

            if (resultSet != null) {
                resultSet.close();
            }
            if (statement != null) {
                statement.close();
            }
            if (connection != null) {
                connection.close();
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGoBackActionPerformed
        this.dispose();
    }// GEN-LAST:event_btnGoBackActionPerformed

    // Save changes made to the profile and override data in the SQL database
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed

        String name = txtFullName.getText();
        String firstname;
        String lastname;
        String login = txtUsername.getText();
        String dateofbirth = txtBirthDate.getText();

        String phonenumber = txtPhoneNum.getText();
        String email = txtEmail.getText();

        if (name.isEmpty() || login.isEmpty() || dateofbirth.isEmpty() || email.isEmpty()) { // edit
            JOptionPane.showMessageDialog(this,
                    "Please fill in all of the text fields", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            String[] nameParts = name.split(" ");
            if (nameParts.length >= 2) {
                firstname = nameParts[0];
                lastname = nameParts[1];
            } else {
                firstname = name;
                lastname = "";
            }
            try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/TransModus", "root",
                    "");
                    PreparedStatement statement = connection.prepareStatement(
                            "INSERT INTO client (firstname, lastname, login, birthday_month, birthday_day, birthday_year, phonenumber, email) VALUES (?, ?, ?, ?, ?, ?, ?, ?)")) {

                // Prepare the SQL statement
                statement.setString(1, firstname);
                statement.setString(2, lastname);
                statement.setString(2, login);
                statement.setString(3, dateofbirth);
                statement.setString(4, phonenumber);
                statement.setString(5, email);

                // Execute the SQL statement
                int rowsAffected = statement.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Your account has been successfully updated!");
                    HomePage hpg = new HomePage();
                    hpg.setVisible(true);
                    hpg.pack();
                    this.dispose();
                }

                // Close the connection
                connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this,
                        "An error occurred while registering your account", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    } // GEN-LAST:event_btnSaveActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField6;
    public javax.swing.JTextField txtBirthDate;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtFullName;
    public javax.swing.JTextField txtPhoneNum;
    public javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
